# -*- coding: utf-8 -*-

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Reloader(object):
    def setupUi(self, Reloader):
        Reloader.setObjectName("Reloader")
        Reloader.resize(319, 164)
        Reloader.setMinimumSize(QtCore.QSize(319, 164))
        Reloader.setMaximumSize(QtCore.QSize(500, 200))
        Reloader.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Reloader.setWhatsThis("")
        Reloader.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.gridLayout = QtWidgets.QGridLayout(Reloader)
        self.gridLayout.setObjectName("gridLayout")
        self.comboPlugin = QtWidgets.QComboBox(Reloader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboPlugin.sizePolicy().hasHeightForWidth())
        self.comboPlugin.setSizePolicy(sizePolicy)
        self.comboPlugin.setMinimumSize(QtCore.QSize(220, 0))
        self.comboPlugin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboPlugin.setObjectName("comboPlugin")
        self.gridLayout.addWidget(self.comboPlugin, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Reloader)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 4)
        self.label = QtWidgets.QLabel(Reloader)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 2)
        self.label.setBuddy(self.comboPlugin)

        self.retranslateUi(Reloader)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Reloader.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Reloader.reject)
        QtCore.QMetaObject.connectSlotsByName(Reloader)

    def retranslateUi(self, Reloader):
        Reloader.setWindowTitle(QtWidgets.QApplication.translate("Reloader", "Script Reloader"))
        self.label.setText(QtWidgets.QApplication.translate("Reloader", "Select a script to reload :"))
        Reloader.messageSuccess.setWindowTitle("Script Reloader")
        msg = QtWidgets.QApplication.translate("Reloader","Script reloaded!")
        Reloader.messageSuccess.setText(msg)